services:
  - type: web
    name: loja-celulares
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PIX_KEY
        sync: false
